// source: rover.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var core_pb = require('./core_pb.js');
goog.object.extend(proto, core_pb);
goog.exportSymbol('proto.bc.rover.MarkedTxsReq', null, global);
goog.exportSymbol('proto.bc.rover.QueuedMarkedTxsResponse', null, global);
goog.exportSymbol('proto.bc.rover.RoverIdent', null, global);
goog.exportSymbol('proto.bc.rover.RoverMessage', null, global);
goog.exportSymbol('proto.bc.rover.RoverMessage.FetchBlock', null, global);
goog.exportSymbol('proto.bc.rover.RoverMessage.LatestBlock', null, global);
goog.exportSymbol('proto.bc.rover.RoverMessage.PayloadCase', null, global);
goog.exportSymbol('proto.bc.rover.RoverMessage.Resync', null, global);
goog.exportSymbol('proto.bc.rover.RoverMessage.Resync.Interval', null, global);
goog.exportSymbol('proto.bc.rover.RoverMessage.RoverBlockRange', null, global);
goog.exportSymbol('proto.bc.rover.RoverMessageType', null, global);
goog.exportSymbol('proto.bc.rover.RoverSyncStatus', null, global);
goog.exportSymbol('proto.bc.rover.SettleTxCheckReq', null, global);
goog.exportSymbol('proto.bc.rover.SettleTxCheckReq.PossibleTransaction', null, global);
goog.exportSymbol('proto.bc.rover.SettleTxCheckResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bc.rover.RoverIdent = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.bc.rover.RoverIdent, jspb.Message);
if (true || goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bc.rover.RoverIdent.displayName = 'proto.bc.rover.RoverIdent';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bc.rover.RoverSyncStatus = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.bc.rover.RoverSyncStatus, jspb.Message);
if (true || goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bc.rover.RoverSyncStatus.displayName = 'proto.bc.rover.RoverSyncStatus';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bc.rover.RoverMessage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.bc.rover.RoverMessage.oneofGroups_);
};
goog.inherits(proto.bc.rover.RoverMessage, jspb.Message);
if (true || goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bc.rover.RoverMessage.displayName = 'proto.bc.rover.RoverMessage';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bc.rover.RoverMessage.FetchBlock = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.bc.rover.RoverMessage.FetchBlock, jspb.Message);
if (true || goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bc.rover.RoverMessage.FetchBlock.displayName = 'proto.bc.rover.RoverMessage.FetchBlock';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bc.rover.RoverMessage.LatestBlock = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.bc.rover.RoverMessage.LatestBlock, jspb.Message);
if (true || goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bc.rover.RoverMessage.LatestBlock.displayName = 'proto.bc.rover.RoverMessage.LatestBlock';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bc.rover.RoverMessage.RoverBlockRange = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.bc.rover.RoverMessage.RoverBlockRange, jspb.Message);
if (true || goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bc.rover.RoverMessage.RoverBlockRange.displayName = 'proto.bc.rover.RoverMessage.RoverBlockRange';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bc.rover.RoverMessage.Resync = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.bc.rover.RoverMessage.Resync.repeatedFields_, null);
};
goog.inherits(proto.bc.rover.RoverMessage.Resync, jspb.Message);
if (true || goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bc.rover.RoverMessage.Resync.displayName = 'proto.bc.rover.RoverMessage.Resync';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bc.rover.RoverMessage.Resync.Interval = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.bc.rover.RoverMessage.Resync.Interval, jspb.Message);
if (true || goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bc.rover.RoverMessage.Resync.Interval.displayName = 'proto.bc.rover.RoverMessage.Resync.Interval';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bc.rover.SettleTxCheckReq = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.bc.rover.SettleTxCheckReq.repeatedFields_, null);
};
goog.inherits(proto.bc.rover.SettleTxCheckReq, jspb.Message);
if (true || goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bc.rover.SettleTxCheckReq.displayName = 'proto.bc.rover.SettleTxCheckReq';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bc.rover.SettleTxCheckReq.PossibleTransaction = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.bc.rover.SettleTxCheckReq.PossibleTransaction, jspb.Message);
if (true || goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bc.rover.SettleTxCheckReq.PossibleTransaction.displayName = 'proto.bc.rover.SettleTxCheckReq.PossibleTransaction';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bc.rover.SettleTxCheckResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.bc.rover.SettleTxCheckResponse.repeatedFields_, null);
};
goog.inherits(proto.bc.rover.SettleTxCheckResponse, jspb.Message);
if (true || goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bc.rover.SettleTxCheckResponse.displayName = 'proto.bc.rover.SettleTxCheckResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bc.rover.MarkedTxsReq = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.bc.rover.MarkedTxsReq.repeatedFields_, null);
};
goog.inherits(proto.bc.rover.MarkedTxsReq, jspb.Message);
if (true || goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bc.rover.MarkedTxsReq.displayName = 'proto.bc.rover.MarkedTxsReq';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bc.rover.QueuedMarkedTxsResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.bc.rover.QueuedMarkedTxsResponse.repeatedFields_, null);
};
goog.inherits(proto.bc.rover.QueuedMarkedTxsResponse, jspb.Message);
if (true || goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bc.rover.QueuedMarkedTxsResponse.displayName = 'proto.bc.rover.QueuedMarkedTxsResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bc.rover.RoverIdent.prototype.toObject = function(opt_includeInstance) {
  return proto.bc.rover.RoverIdent.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bc.rover.RoverIdent} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bc.rover.RoverIdent.toObject = function(includeInstance, msg) {
  var f, obj = {
    roverName: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bc.rover.RoverIdent}
 */
proto.bc.rover.RoverIdent.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bc.rover.RoverIdent;
  return proto.bc.rover.RoverIdent.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bc.rover.RoverIdent} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bc.rover.RoverIdent}
 */
proto.bc.rover.RoverIdent.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setRoverName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bc.rover.RoverIdent.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bc.rover.RoverIdent.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bc.rover.RoverIdent} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bc.rover.RoverIdent.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRoverName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string rover_name = 1;
 * @return {string}
 */
proto.bc.rover.RoverIdent.prototype.getRoverName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.bc.rover.RoverIdent} returns this
 */
proto.bc.rover.RoverIdent.prototype.setRoverName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bc.rover.RoverSyncStatus.prototype.toObject = function(opt_includeInstance) {
  return proto.bc.rover.RoverSyncStatus.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bc.rover.RoverSyncStatus} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bc.rover.RoverSyncStatus.toObject = function(includeInstance, msg) {
  var f, obj = {
    roverName: jspb.Message.getFieldWithDefault(msg, 1, ""),
    status: jspb.Message.getBooleanFieldWithDefault(msg, 2, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bc.rover.RoverSyncStatus}
 */
proto.bc.rover.RoverSyncStatus.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bc.rover.RoverSyncStatus;
  return proto.bc.rover.RoverSyncStatus.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bc.rover.RoverSyncStatus} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bc.rover.RoverSyncStatus}
 */
proto.bc.rover.RoverSyncStatus.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setRoverName(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setStatus(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bc.rover.RoverSyncStatus.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bc.rover.RoverSyncStatus.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bc.rover.RoverSyncStatus} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bc.rover.RoverSyncStatus.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRoverName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getStatus();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
};


/**
 * optional string rover_name = 1;
 * @return {string}
 */
proto.bc.rover.RoverSyncStatus.prototype.getRoverName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.bc.rover.RoverSyncStatus} returns this
 */
proto.bc.rover.RoverSyncStatus.prototype.setRoverName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional bool status = 2;
 * @return {boolean}
 */
proto.bc.rover.RoverSyncStatus.prototype.getStatus = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.bc.rover.RoverSyncStatus} returns this
 */
proto.bc.rover.RoverSyncStatus.prototype.setStatus = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.bc.rover.RoverMessage.oneofGroups_ = [[2,3,4,5]];

/**
 * @enum {number}
 */
proto.bc.rover.RoverMessage.PayloadCase = {
  PAYLOAD_NOT_SET: 0,
  RESYNC: 2,
  FETCH_BLOCK: 3,
  ROVER_BLOCK_RANGE: 4,
  LATEST_BLOCK: 5
};

/**
 * @return {proto.bc.rover.RoverMessage.PayloadCase}
 */
proto.bc.rover.RoverMessage.prototype.getPayloadCase = function() {
  return /** @type {proto.bc.rover.RoverMessage.PayloadCase} */(jspb.Message.computeOneofCase(this, proto.bc.rover.RoverMessage.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bc.rover.RoverMessage.prototype.toObject = function(opt_includeInstance) {
  return proto.bc.rover.RoverMessage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bc.rover.RoverMessage} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bc.rover.RoverMessage.toObject = function(includeInstance, msg) {
  var f, obj = {
    type: jspb.Message.getFieldWithDefault(msg, 1, 0),
    resync: (f = msg.getResync()) && proto.bc.rover.RoverMessage.Resync.toObject(includeInstance, f),
    fetchBlock: (f = msg.getFetchBlock()) && proto.bc.rover.RoverMessage.FetchBlock.toObject(includeInstance, f),
    roverBlockRange: (f = msg.getRoverBlockRange()) && proto.bc.rover.RoverMessage.RoverBlockRange.toObject(includeInstance, f),
    latestBlock: (f = msg.getLatestBlock()) && proto.bc.rover.RoverMessage.LatestBlock.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bc.rover.RoverMessage}
 */
proto.bc.rover.RoverMessage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bc.rover.RoverMessage;
  return proto.bc.rover.RoverMessage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bc.rover.RoverMessage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bc.rover.RoverMessage}
 */
proto.bc.rover.RoverMessage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.bc.rover.RoverMessageType} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 2:
      var value = new proto.bc.rover.RoverMessage.Resync;
      reader.readMessage(value,proto.bc.rover.RoverMessage.Resync.deserializeBinaryFromReader);
      msg.setResync(value);
      break;
    case 3:
      var value = new proto.bc.rover.RoverMessage.FetchBlock;
      reader.readMessage(value,proto.bc.rover.RoverMessage.FetchBlock.deserializeBinaryFromReader);
      msg.setFetchBlock(value);
      break;
    case 4:
      var value = new proto.bc.rover.RoverMessage.RoverBlockRange;
      reader.readMessage(value,proto.bc.rover.RoverMessage.RoverBlockRange.deserializeBinaryFromReader);
      msg.setRoverBlockRange(value);
      break;
    case 5:
      var value = new proto.bc.rover.RoverMessage.LatestBlock;
      reader.readMessage(value,proto.bc.rover.RoverMessage.LatestBlock.deserializeBinaryFromReader);
      msg.setLatestBlock(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bc.rover.RoverMessage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bc.rover.RoverMessage.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bc.rover.RoverMessage} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bc.rover.RoverMessage.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getResync();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.bc.rover.RoverMessage.Resync.serializeBinaryToWriter
    );
  }
  f = message.getFetchBlock();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.bc.rover.RoverMessage.FetchBlock.serializeBinaryToWriter
    );
  }
  f = message.getRoverBlockRange();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.bc.rover.RoverMessage.RoverBlockRange.serializeBinaryToWriter
    );
  }
  f = message.getLatestBlock();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.bc.rover.RoverMessage.LatestBlock.serializeBinaryToWriter
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bc.rover.RoverMessage.FetchBlock.prototype.toObject = function(opt_includeInstance) {
  return proto.bc.rover.RoverMessage.FetchBlock.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bc.rover.RoverMessage.FetchBlock} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bc.rover.RoverMessage.FetchBlock.toObject = function(includeInstance, msg) {
  var f, obj = {
    fromBlock: (f = msg.getFromBlock()) && core_pb.Block.toObject(includeInstance, f),
    toBlock: (f = msg.getToBlock()) && core_pb.Block.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bc.rover.RoverMessage.FetchBlock}
 */
proto.bc.rover.RoverMessage.FetchBlock.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bc.rover.RoverMessage.FetchBlock;
  return proto.bc.rover.RoverMessage.FetchBlock.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bc.rover.RoverMessage.FetchBlock} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bc.rover.RoverMessage.FetchBlock}
 */
proto.bc.rover.RoverMessage.FetchBlock.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new core_pb.Block;
      reader.readMessage(value,core_pb.Block.deserializeBinaryFromReader);
      msg.setFromBlock(value);
      break;
    case 2:
      var value = new core_pb.Block;
      reader.readMessage(value,core_pb.Block.deserializeBinaryFromReader);
      msg.setToBlock(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bc.rover.RoverMessage.FetchBlock.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bc.rover.RoverMessage.FetchBlock.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bc.rover.RoverMessage.FetchBlock} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bc.rover.RoverMessage.FetchBlock.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFromBlock();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      core_pb.Block.serializeBinaryToWriter
    );
  }
  f = message.getToBlock();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      core_pb.Block.serializeBinaryToWriter
    );
  }
};


/**
 * optional bc.core.Block from_block = 1;
 * @return {?proto.bc.core.Block}
 */
proto.bc.rover.RoverMessage.FetchBlock.prototype.getFromBlock = function() {
  return /** @type{?proto.bc.core.Block} */ (
    jspb.Message.getWrapperField(this, core_pb.Block, 1));
};


/**
 * @param {?proto.bc.core.Block|undefined} value
 * @return {!proto.bc.rover.RoverMessage.FetchBlock} returns this
*/
proto.bc.rover.RoverMessage.FetchBlock.prototype.setFromBlock = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bc.rover.RoverMessage.FetchBlock} returns this
 */
proto.bc.rover.RoverMessage.FetchBlock.prototype.clearFromBlock = function() {
  return this.setFromBlock(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bc.rover.RoverMessage.FetchBlock.prototype.hasFromBlock = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional bc.core.Block to_block = 2;
 * @return {?proto.bc.core.Block}
 */
proto.bc.rover.RoverMessage.FetchBlock.prototype.getToBlock = function() {
  return /** @type{?proto.bc.core.Block} */ (
    jspb.Message.getWrapperField(this, core_pb.Block, 2));
};


/**
 * @param {?proto.bc.core.Block|undefined} value
 * @return {!proto.bc.rover.RoverMessage.FetchBlock} returns this
*/
proto.bc.rover.RoverMessage.FetchBlock.prototype.setToBlock = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bc.rover.RoverMessage.FetchBlock} returns this
 */
proto.bc.rover.RoverMessage.FetchBlock.prototype.clearToBlock = function() {
  return this.setToBlock(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bc.rover.RoverMessage.FetchBlock.prototype.hasToBlock = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bc.rover.RoverMessage.LatestBlock.prototype.toObject = function(opt_includeInstance) {
  return proto.bc.rover.RoverMessage.LatestBlock.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bc.rover.RoverMessage.LatestBlock} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bc.rover.RoverMessage.LatestBlock.toObject = function(includeInstance, msg) {
  var f, obj = {
    roverName: jspb.Message.getFieldWithDefault(msg, 1, ""),
    block: (f = msg.getBlock()) && core_pb.Block.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bc.rover.RoverMessage.LatestBlock}
 */
proto.bc.rover.RoverMessage.LatestBlock.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bc.rover.RoverMessage.LatestBlock;
  return proto.bc.rover.RoverMessage.LatestBlock.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bc.rover.RoverMessage.LatestBlock} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bc.rover.RoverMessage.LatestBlock}
 */
proto.bc.rover.RoverMessage.LatestBlock.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setRoverName(value);
      break;
    case 2:
      var value = new core_pb.Block;
      reader.readMessage(value,core_pb.Block.deserializeBinaryFromReader);
      msg.setBlock(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bc.rover.RoverMessage.LatestBlock.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bc.rover.RoverMessage.LatestBlock.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bc.rover.RoverMessage.LatestBlock} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bc.rover.RoverMessage.LatestBlock.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRoverName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getBlock();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      core_pb.Block.serializeBinaryToWriter
    );
  }
};


/**
 * optional string rover_name = 1;
 * @return {string}
 */
proto.bc.rover.RoverMessage.LatestBlock.prototype.getRoverName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.bc.rover.RoverMessage.LatestBlock} returns this
 */
proto.bc.rover.RoverMessage.LatestBlock.prototype.setRoverName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional bc.core.Block block = 2;
 * @return {?proto.bc.core.Block}
 */
proto.bc.rover.RoverMessage.LatestBlock.prototype.getBlock = function() {
  return /** @type{?proto.bc.core.Block} */ (
    jspb.Message.getWrapperField(this, core_pb.Block, 2));
};


/**
 * @param {?proto.bc.core.Block|undefined} value
 * @return {!proto.bc.rover.RoverMessage.LatestBlock} returns this
*/
proto.bc.rover.RoverMessage.LatestBlock.prototype.setBlock = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bc.rover.RoverMessage.LatestBlock} returns this
 */
proto.bc.rover.RoverMessage.LatestBlock.prototype.clearBlock = function() {
  return this.setBlock(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bc.rover.RoverMessage.LatestBlock.prototype.hasBlock = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bc.rover.RoverMessage.RoverBlockRange.prototype.toObject = function(opt_includeInstance) {
  return proto.bc.rover.RoverMessage.RoverBlockRange.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bc.rover.RoverMessage.RoverBlockRange} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bc.rover.RoverMessage.RoverBlockRange.toObject = function(includeInstance, msg) {
  var f, obj = {
    roverName: jspb.Message.getFieldWithDefault(msg, 1, ""),
    highestHeight: jspb.Message.getFieldWithDefault(msg, 2, 0),
    lowestHeight: jspb.Message.getFieldWithDefault(msg, 3, 0),
    highestHash: jspb.Message.getFieldWithDefault(msg, 4, ""),
    lowestHash: jspb.Message.getFieldWithDefault(msg, 5, ""),
    synced: jspb.Message.getFieldWithDefault(msg, 6, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bc.rover.RoverMessage.RoverBlockRange}
 */
proto.bc.rover.RoverMessage.RoverBlockRange.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bc.rover.RoverMessage.RoverBlockRange;
  return proto.bc.rover.RoverMessage.RoverBlockRange.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bc.rover.RoverMessage.RoverBlockRange} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bc.rover.RoverMessage.RoverBlockRange}
 */
proto.bc.rover.RoverMessage.RoverBlockRange.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setRoverName(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setHighestHeight(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setLowestHeight(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setHighestHash(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setLowestHash(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setSynced(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bc.rover.RoverMessage.RoverBlockRange.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bc.rover.RoverMessage.RoverBlockRange.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bc.rover.RoverMessage.RoverBlockRange} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bc.rover.RoverMessage.RoverBlockRange.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRoverName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getHighestHeight();
  if (f !== 0) {
    writer.writeUint64(
      2,
      f
    );
  }
  f = message.getLowestHeight();
  if (f !== 0) {
    writer.writeUint64(
      3,
      f
    );
  }
  f = message.getHighestHash();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getLowestHash();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getSynced();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
};


/**
 * optional string rover_name = 1;
 * @return {string}
 */
proto.bc.rover.RoverMessage.RoverBlockRange.prototype.getRoverName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.bc.rover.RoverMessage.RoverBlockRange} returns this
 */
proto.bc.rover.RoverMessage.RoverBlockRange.prototype.setRoverName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional uint64 highest_height = 2;
 * @return {number}
 */
proto.bc.rover.RoverMessage.RoverBlockRange.prototype.getHighestHeight = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.bc.rover.RoverMessage.RoverBlockRange} returns this
 */
proto.bc.rover.RoverMessage.RoverBlockRange.prototype.setHighestHeight = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional uint64 lowest_height = 3;
 * @return {number}
 */
proto.bc.rover.RoverMessage.RoverBlockRange.prototype.getLowestHeight = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.bc.rover.RoverMessage.RoverBlockRange} returns this
 */
proto.bc.rover.RoverMessage.RoverBlockRange.prototype.setLowestHeight = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional string highest_hash = 4;
 * @return {string}
 */
proto.bc.rover.RoverMessage.RoverBlockRange.prototype.getHighestHash = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.bc.rover.RoverMessage.RoverBlockRange} returns this
 */
proto.bc.rover.RoverMessage.RoverBlockRange.prototype.setHighestHash = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string lowest_hash = 5;
 * @return {string}
 */
proto.bc.rover.RoverMessage.RoverBlockRange.prototype.getLowestHash = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.bc.rover.RoverMessage.RoverBlockRange} returns this
 */
proto.bc.rover.RoverMessage.RoverBlockRange.prototype.setLowestHash = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string synced = 6;
 * @return {string}
 */
proto.bc.rover.RoverMessage.RoverBlockRange.prototype.getSynced = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.bc.rover.RoverMessage.RoverBlockRange} returns this
 */
proto.bc.rover.RoverMessage.RoverBlockRange.prototype.setSynced = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.bc.rover.RoverMessage.Resync.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bc.rover.RoverMessage.Resync.prototype.toObject = function(opt_includeInstance) {
  return proto.bc.rover.RoverMessage.Resync.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bc.rover.RoverMessage.Resync} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bc.rover.RoverMessage.Resync.toObject = function(includeInstance, msg) {
  var f, obj = {
    latestBlock: (f = msg.getLatestBlock()) && core_pb.Block.toObject(includeInstance, f),
    intervalsList: jspb.Message.toObjectList(msg.getIntervalsList(),
    proto.bc.rover.RoverMessage.Resync.Interval.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bc.rover.RoverMessage.Resync}
 */
proto.bc.rover.RoverMessage.Resync.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bc.rover.RoverMessage.Resync;
  return proto.bc.rover.RoverMessage.Resync.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bc.rover.RoverMessage.Resync} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bc.rover.RoverMessage.Resync}
 */
proto.bc.rover.RoverMessage.Resync.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new core_pb.Block;
      reader.readMessage(value,core_pb.Block.deserializeBinaryFromReader);
      msg.setLatestBlock(value);
      break;
    case 2:
      var value = new proto.bc.rover.RoverMessage.Resync.Interval;
      reader.readMessage(value,proto.bc.rover.RoverMessage.Resync.Interval.deserializeBinaryFromReader);
      msg.addIntervals(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bc.rover.RoverMessage.Resync.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bc.rover.RoverMessage.Resync.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bc.rover.RoverMessage.Resync} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bc.rover.RoverMessage.Resync.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getLatestBlock();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      core_pb.Block.serializeBinaryToWriter
    );
  }
  f = message.getIntervalsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.bc.rover.RoverMessage.Resync.Interval.serializeBinaryToWriter
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bc.rover.RoverMessage.Resync.Interval.prototype.toObject = function(opt_includeInstance) {
  return proto.bc.rover.RoverMessage.Resync.Interval.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bc.rover.RoverMessage.Resync.Interval} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bc.rover.RoverMessage.Resync.Interval.toObject = function(includeInstance, msg) {
  var f, obj = {
    fromBlock: (f = msg.getFromBlock()) && core_pb.Block.toObject(includeInstance, f),
    toBlock: (f = msg.getToBlock()) && core_pb.Block.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bc.rover.RoverMessage.Resync.Interval}
 */
proto.bc.rover.RoverMessage.Resync.Interval.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bc.rover.RoverMessage.Resync.Interval;
  return proto.bc.rover.RoverMessage.Resync.Interval.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bc.rover.RoverMessage.Resync.Interval} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bc.rover.RoverMessage.Resync.Interval}
 */
proto.bc.rover.RoverMessage.Resync.Interval.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new core_pb.Block;
      reader.readMessage(value,core_pb.Block.deserializeBinaryFromReader);
      msg.setFromBlock(value);
      break;
    case 2:
      var value = new core_pb.Block;
      reader.readMessage(value,core_pb.Block.deserializeBinaryFromReader);
      msg.setToBlock(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bc.rover.RoverMessage.Resync.Interval.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bc.rover.RoverMessage.Resync.Interval.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bc.rover.RoverMessage.Resync.Interval} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bc.rover.RoverMessage.Resync.Interval.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFromBlock();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      core_pb.Block.serializeBinaryToWriter
    );
  }
  f = message.getToBlock();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      core_pb.Block.serializeBinaryToWriter
    );
  }
};


/**
 * optional bc.core.Block from_block = 1;
 * @return {?proto.bc.core.Block}
 */
proto.bc.rover.RoverMessage.Resync.Interval.prototype.getFromBlock = function() {
  return /** @type{?proto.bc.core.Block} */ (
    jspb.Message.getWrapperField(this, core_pb.Block, 1));
};


/**
 * @param {?proto.bc.core.Block|undefined} value
 * @return {!proto.bc.rover.RoverMessage.Resync.Interval} returns this
*/
proto.bc.rover.RoverMessage.Resync.Interval.prototype.setFromBlock = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bc.rover.RoverMessage.Resync.Interval} returns this
 */
proto.bc.rover.RoverMessage.Resync.Interval.prototype.clearFromBlock = function() {
  return this.setFromBlock(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bc.rover.RoverMessage.Resync.Interval.prototype.hasFromBlock = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional bc.core.Block to_block = 2;
 * @return {?proto.bc.core.Block}
 */
proto.bc.rover.RoverMessage.Resync.Interval.prototype.getToBlock = function() {
  return /** @type{?proto.bc.core.Block} */ (
    jspb.Message.getWrapperField(this, core_pb.Block, 2));
};


/**
 * @param {?proto.bc.core.Block|undefined} value
 * @return {!proto.bc.rover.RoverMessage.Resync.Interval} returns this
*/
proto.bc.rover.RoverMessage.Resync.Interval.prototype.setToBlock = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bc.rover.RoverMessage.Resync.Interval} returns this
 */
proto.bc.rover.RoverMessage.Resync.Interval.prototype.clearToBlock = function() {
  return this.setToBlock(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bc.rover.RoverMessage.Resync.Interval.prototype.hasToBlock = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional bc.core.Block latest_block = 1;
 * @return {?proto.bc.core.Block}
 */
proto.bc.rover.RoverMessage.Resync.prototype.getLatestBlock = function() {
  return /** @type{?proto.bc.core.Block} */ (
    jspb.Message.getWrapperField(this, core_pb.Block, 1));
};


/**
 * @param {?proto.bc.core.Block|undefined} value
 * @return {!proto.bc.rover.RoverMessage.Resync} returns this
*/
proto.bc.rover.RoverMessage.Resync.prototype.setLatestBlock = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bc.rover.RoverMessage.Resync} returns this
 */
proto.bc.rover.RoverMessage.Resync.prototype.clearLatestBlock = function() {
  return this.setLatestBlock(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bc.rover.RoverMessage.Resync.prototype.hasLatestBlock = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated Interval intervals = 2;
 * @return {!Array<!proto.bc.rover.RoverMessage.Resync.Interval>}
 */
proto.bc.rover.RoverMessage.Resync.prototype.getIntervalsList = function() {
  return /** @type{!Array<!proto.bc.rover.RoverMessage.Resync.Interval>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.bc.rover.RoverMessage.Resync.Interval, 2));
};


/**
 * @param {!Array<!proto.bc.rover.RoverMessage.Resync.Interval>} value
 * @return {!proto.bc.rover.RoverMessage.Resync} returns this
*/
proto.bc.rover.RoverMessage.Resync.prototype.setIntervalsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.bc.rover.RoverMessage.Resync.Interval=} opt_value
 * @param {number=} opt_index
 * @return {!proto.bc.rover.RoverMessage.Resync.Interval}
 */
proto.bc.rover.RoverMessage.Resync.prototype.addIntervals = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.bc.rover.RoverMessage.Resync.Interval, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.bc.rover.RoverMessage.Resync} returns this
 */
proto.bc.rover.RoverMessage.Resync.prototype.clearIntervalsList = function() {
  return this.setIntervalsList([]);
};


/**
 * optional RoverMessageType type = 1;
 * @return {!proto.bc.rover.RoverMessageType}
 */
proto.bc.rover.RoverMessage.prototype.getType = function() {
  return /** @type {!proto.bc.rover.RoverMessageType} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.bc.rover.RoverMessageType} value
 * @return {!proto.bc.rover.RoverMessage} returns this
 */
proto.bc.rover.RoverMessage.prototype.setType = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional Resync resync = 2;
 * @return {?proto.bc.rover.RoverMessage.Resync}
 */
proto.bc.rover.RoverMessage.prototype.getResync = function() {
  return /** @type{?proto.bc.rover.RoverMessage.Resync} */ (
    jspb.Message.getWrapperField(this, proto.bc.rover.RoverMessage.Resync, 2));
};


/**
 * @param {?proto.bc.rover.RoverMessage.Resync|undefined} value
 * @return {!proto.bc.rover.RoverMessage} returns this
*/
proto.bc.rover.RoverMessage.prototype.setResync = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.bc.rover.RoverMessage.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bc.rover.RoverMessage} returns this
 */
proto.bc.rover.RoverMessage.prototype.clearResync = function() {
  return this.setResync(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bc.rover.RoverMessage.prototype.hasResync = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional FetchBlock fetch_block = 3;
 * @return {?proto.bc.rover.RoverMessage.FetchBlock}
 */
proto.bc.rover.RoverMessage.prototype.getFetchBlock = function() {
  return /** @type{?proto.bc.rover.RoverMessage.FetchBlock} */ (
    jspb.Message.getWrapperField(this, proto.bc.rover.RoverMessage.FetchBlock, 3));
};


/**
 * @param {?proto.bc.rover.RoverMessage.FetchBlock|undefined} value
 * @return {!proto.bc.rover.RoverMessage} returns this
*/
proto.bc.rover.RoverMessage.prototype.setFetchBlock = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.bc.rover.RoverMessage.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bc.rover.RoverMessage} returns this
 */
proto.bc.rover.RoverMessage.prototype.clearFetchBlock = function() {
  return this.setFetchBlock(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bc.rover.RoverMessage.prototype.hasFetchBlock = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional RoverBlockRange rover_block_range = 4;
 * @return {?proto.bc.rover.RoverMessage.RoverBlockRange}
 */
proto.bc.rover.RoverMessage.prototype.getRoverBlockRange = function() {
  return /** @type{?proto.bc.rover.RoverMessage.RoverBlockRange} */ (
    jspb.Message.getWrapperField(this, proto.bc.rover.RoverMessage.RoverBlockRange, 4));
};


/**
 * @param {?proto.bc.rover.RoverMessage.RoverBlockRange|undefined} value
 * @return {!proto.bc.rover.RoverMessage} returns this
*/
proto.bc.rover.RoverMessage.prototype.setRoverBlockRange = function(value) {
  return jspb.Message.setOneofWrapperField(this, 4, proto.bc.rover.RoverMessage.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bc.rover.RoverMessage} returns this
 */
proto.bc.rover.RoverMessage.prototype.clearRoverBlockRange = function() {
  return this.setRoverBlockRange(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bc.rover.RoverMessage.prototype.hasRoverBlockRange = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional LatestBlock latest_block = 5;
 * @return {?proto.bc.rover.RoverMessage.LatestBlock}
 */
proto.bc.rover.RoverMessage.prototype.getLatestBlock = function() {
  return /** @type{?proto.bc.rover.RoverMessage.LatestBlock} */ (
    jspb.Message.getWrapperField(this, proto.bc.rover.RoverMessage.LatestBlock, 5));
};


/**
 * @param {?proto.bc.rover.RoverMessage.LatestBlock|undefined} value
 * @return {!proto.bc.rover.RoverMessage} returns this
*/
proto.bc.rover.RoverMessage.prototype.setLatestBlock = function(value) {
  return jspb.Message.setOneofWrapperField(this, 5, proto.bc.rover.RoverMessage.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bc.rover.RoverMessage} returns this
 */
proto.bc.rover.RoverMessage.prototype.clearLatestBlock = function() {
  return this.setLatestBlock(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bc.rover.RoverMessage.prototype.hasLatestBlock = function() {
  return jspb.Message.getField(this, 5) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.bc.rover.SettleTxCheckReq.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bc.rover.SettleTxCheckReq.prototype.toObject = function(opt_includeInstance) {
  return proto.bc.rover.SettleTxCheckReq.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bc.rover.SettleTxCheckReq} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bc.rover.SettleTxCheckReq.toObject = function(includeInstance, msg) {
  var f, obj = {
    possibleTransactionsList: jspb.Message.toObjectList(msg.getPossibleTransactionsList(),
    proto.bc.rover.SettleTxCheckReq.PossibleTransaction.toObject, includeInstance),
    blockHash: jspb.Message.getFieldWithDefault(msg, 2, ""),
    bridgedChain: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bc.rover.SettleTxCheckReq}
 */
proto.bc.rover.SettleTxCheckReq.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bc.rover.SettleTxCheckReq;
  return proto.bc.rover.SettleTxCheckReq.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bc.rover.SettleTxCheckReq} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bc.rover.SettleTxCheckReq}
 */
proto.bc.rover.SettleTxCheckReq.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.bc.rover.SettleTxCheckReq.PossibleTransaction;
      reader.readMessage(value,proto.bc.rover.SettleTxCheckReq.PossibleTransaction.deserializeBinaryFromReader);
      msg.addPossibleTransactions(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setBlockHash(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setBridgedChain(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bc.rover.SettleTxCheckReq.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bc.rover.SettleTxCheckReq.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bc.rover.SettleTxCheckReq} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bc.rover.SettleTxCheckReq.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPossibleTransactionsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.bc.rover.SettleTxCheckReq.PossibleTransaction.serializeBinaryToWriter
    );
  }
  f = message.getBlockHash();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getBridgedChain();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bc.rover.SettleTxCheckReq.PossibleTransaction.prototype.toObject = function(opt_includeInstance) {
  return proto.bc.rover.SettleTxCheckReq.PossibleTransaction.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bc.rover.SettleTxCheckReq.PossibleTransaction} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bc.rover.SettleTxCheckReq.PossibleTransaction.toObject = function(includeInstance, msg) {
  var f, obj = {
    addrTo: jspb.Message.getFieldWithDefault(msg, 1, ""),
    addrFrom: jspb.Message.getFieldWithDefault(msg, 2, ""),
    value: msg.getValue_asB64(),
    bridgedChain: jspb.Message.getFieldWithDefault(msg, 4, ""),
    txId: jspb.Message.getFieldWithDefault(msg, 5, ""),
    blockHeight: jspb.Message.getFieldWithDefault(msg, 6, 0),
    tokenType: jspb.Message.getFieldWithDefault(msg, 7, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bc.rover.SettleTxCheckReq.PossibleTransaction}
 */
proto.bc.rover.SettleTxCheckReq.PossibleTransaction.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bc.rover.SettleTxCheckReq.PossibleTransaction;
  return proto.bc.rover.SettleTxCheckReq.PossibleTransaction.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bc.rover.SettleTxCheckReq.PossibleTransaction} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bc.rover.SettleTxCheckReq.PossibleTransaction}
 */
proto.bc.rover.SettleTxCheckReq.PossibleTransaction.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setAddrTo(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setAddrFrom(value);
      break;
    case 3:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setValue(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setBridgedChain(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setTxId(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setBlockHeight(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setTokenType(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bc.rover.SettleTxCheckReq.PossibleTransaction.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bc.rover.SettleTxCheckReq.PossibleTransaction.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bc.rover.SettleTxCheckReq.PossibleTransaction} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bc.rover.SettleTxCheckReq.PossibleTransaction.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAddrTo();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getAddrFrom();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getValue_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      3,
      f
    );
  }
  f = message.getBridgedChain();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getTxId();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getBlockHeight();
  if (f !== 0) {
    writer.writeUint64(
      6,
      f
    );
  }
  f = message.getTokenType();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
};


/**
 * optional string addr_to = 1;
 * @return {string}
 */
proto.bc.rover.SettleTxCheckReq.PossibleTransaction.prototype.getAddrTo = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.bc.rover.SettleTxCheckReq.PossibleTransaction} returns this
 */
proto.bc.rover.SettleTxCheckReq.PossibleTransaction.prototype.setAddrTo = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string addr_from = 2;
 * @return {string}
 */
proto.bc.rover.SettleTxCheckReq.PossibleTransaction.prototype.getAddrFrom = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.bc.rover.SettleTxCheckReq.PossibleTransaction} returns this
 */
proto.bc.rover.SettleTxCheckReq.PossibleTransaction.prototype.setAddrFrom = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional bytes value = 3;
 * @return {!(string|Uint8Array)}
 */
proto.bc.rover.SettleTxCheckReq.PossibleTransaction.prototype.getValue = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * optional bytes value = 3;
 * This is a type-conversion wrapper around `getValue()`
 * @return {string}
 */
proto.bc.rover.SettleTxCheckReq.PossibleTransaction.prototype.getValue_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getValue()));
};


/**
 * optional bytes value = 3;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getValue()`
 * @return {!Uint8Array}
 */
proto.bc.rover.SettleTxCheckReq.PossibleTransaction.prototype.getValue_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getValue()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.bc.rover.SettleTxCheckReq.PossibleTransaction} returns this
 */
proto.bc.rover.SettleTxCheckReq.PossibleTransaction.prototype.setValue = function(value) {
  return jspb.Message.setProto3BytesField(this, 3, value);
};


/**
 * optional string bridged_chain = 4;
 * @return {string}
 */
proto.bc.rover.SettleTxCheckReq.PossibleTransaction.prototype.getBridgedChain = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.bc.rover.SettleTxCheckReq.PossibleTransaction} returns this
 */
proto.bc.rover.SettleTxCheckReq.PossibleTransaction.prototype.setBridgedChain = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string tx_id = 5;
 * @return {string}
 */
proto.bc.rover.SettleTxCheckReq.PossibleTransaction.prototype.getTxId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.bc.rover.SettleTxCheckReq.PossibleTransaction} returns this
 */
proto.bc.rover.SettleTxCheckReq.PossibleTransaction.prototype.setTxId = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional uint64 block_height = 6;
 * @return {number}
 */
proto.bc.rover.SettleTxCheckReq.PossibleTransaction.prototype.getBlockHeight = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.bc.rover.SettleTxCheckReq.PossibleTransaction} returns this
 */
proto.bc.rover.SettleTxCheckReq.PossibleTransaction.prototype.setBlockHeight = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional string token_type = 7;
 * @return {string}
 */
proto.bc.rover.SettleTxCheckReq.PossibleTransaction.prototype.getTokenType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.bc.rover.SettleTxCheckReq.PossibleTransaction} returns this
 */
proto.bc.rover.SettleTxCheckReq.PossibleTransaction.prototype.setTokenType = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * repeated PossibleTransaction possible_transactions = 1;
 * @return {!Array<!proto.bc.rover.SettleTxCheckReq.PossibleTransaction>}
 */
proto.bc.rover.SettleTxCheckReq.prototype.getPossibleTransactionsList = function() {
  return /** @type{!Array<!proto.bc.rover.SettleTxCheckReq.PossibleTransaction>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.bc.rover.SettleTxCheckReq.PossibleTransaction, 1));
};


/**
 * @param {!Array<!proto.bc.rover.SettleTxCheckReq.PossibleTransaction>} value
 * @return {!proto.bc.rover.SettleTxCheckReq} returns this
*/
proto.bc.rover.SettleTxCheckReq.prototype.setPossibleTransactionsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.bc.rover.SettleTxCheckReq.PossibleTransaction=} opt_value
 * @param {number=} opt_index
 * @return {!proto.bc.rover.SettleTxCheckReq.PossibleTransaction}
 */
proto.bc.rover.SettleTxCheckReq.prototype.addPossibleTransactions = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.bc.rover.SettleTxCheckReq.PossibleTransaction, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.bc.rover.SettleTxCheckReq} returns this
 */
proto.bc.rover.SettleTxCheckReq.prototype.clearPossibleTransactionsList = function() {
  return this.setPossibleTransactionsList([]);
};


/**
 * optional string block_hash = 2;
 * @return {string}
 */
proto.bc.rover.SettleTxCheckReq.prototype.getBlockHash = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.bc.rover.SettleTxCheckReq} returns this
 */
proto.bc.rover.SettleTxCheckReq.prototype.setBlockHash = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string bridged_chain = 3;
 * @return {string}
 */
proto.bc.rover.SettleTxCheckReq.prototype.getBridgedChain = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.bc.rover.SettleTxCheckReq} returns this
 */
proto.bc.rover.SettleTxCheckReq.prototype.setBridgedChain = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.bc.rover.SettleTxCheckResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bc.rover.SettleTxCheckResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.bc.rover.SettleTxCheckResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bc.rover.SettleTxCheckResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bc.rover.SettleTxCheckResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    markedTransactionsList: jspb.Message.toObjectList(msg.getMarkedTransactionsList(),
    core_pb.MarkedTransaction.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bc.rover.SettleTxCheckResponse}
 */
proto.bc.rover.SettleTxCheckResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bc.rover.SettleTxCheckResponse;
  return proto.bc.rover.SettleTxCheckResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bc.rover.SettleTxCheckResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bc.rover.SettleTxCheckResponse}
 */
proto.bc.rover.SettleTxCheckResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new core_pb.MarkedTransaction;
      reader.readMessage(value,core_pb.MarkedTransaction.deserializeBinaryFromReader);
      msg.addMarkedTransactions(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bc.rover.SettleTxCheckResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bc.rover.SettleTxCheckResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bc.rover.SettleTxCheckResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bc.rover.SettleTxCheckResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMarkedTransactionsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      core_pb.MarkedTransaction.serializeBinaryToWriter
    );
  }
};


/**
 * repeated bc.core.MarkedTransaction marked_transactions = 1;
 * @return {!Array<!proto.bc.core.MarkedTransaction>}
 */
proto.bc.rover.SettleTxCheckResponse.prototype.getMarkedTransactionsList = function() {
  return /** @type{!Array<!proto.bc.core.MarkedTransaction>} */ (
    jspb.Message.getRepeatedWrapperField(this, core_pb.MarkedTransaction, 1));
};


/**
 * @param {!Array<!proto.bc.core.MarkedTransaction>} value
 * @return {!proto.bc.rover.SettleTxCheckResponse} returns this
*/
proto.bc.rover.SettleTxCheckResponse.prototype.setMarkedTransactionsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.bc.core.MarkedTransaction=} opt_value
 * @param {number=} opt_index
 * @return {!proto.bc.core.MarkedTransaction}
 */
proto.bc.rover.SettleTxCheckResponse.prototype.addMarkedTransactions = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.bc.core.MarkedTransaction, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.bc.rover.SettleTxCheckResponse} returns this
 */
proto.bc.rover.SettleTxCheckResponse.prototype.clearMarkedTransactionsList = function() {
  return this.setMarkedTransactionsList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.bc.rover.MarkedTxsReq.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bc.rover.MarkedTxsReq.prototype.toObject = function(opt_includeInstance) {
  return proto.bc.rover.MarkedTxsReq.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bc.rover.MarkedTxsReq} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bc.rover.MarkedTxsReq.toObject = function(includeInstance, msg) {
  var f, obj = {
    markedTransactionsList: jspb.Message.toObjectList(msg.getMarkedTransactionsList(),
    core_pb.MarkedTransaction.toObject, includeInstance),
    blockHash: jspb.Message.getFieldWithDefault(msg, 2, ""),
    blockchain: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bc.rover.MarkedTxsReq}
 */
proto.bc.rover.MarkedTxsReq.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bc.rover.MarkedTxsReq;
  return proto.bc.rover.MarkedTxsReq.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bc.rover.MarkedTxsReq} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bc.rover.MarkedTxsReq}
 */
proto.bc.rover.MarkedTxsReq.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new core_pb.MarkedTransaction;
      reader.readMessage(value,core_pb.MarkedTransaction.deserializeBinaryFromReader);
      msg.addMarkedTransactions(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setBlockHash(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setBlockchain(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bc.rover.MarkedTxsReq.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bc.rover.MarkedTxsReq.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bc.rover.MarkedTxsReq} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bc.rover.MarkedTxsReq.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMarkedTransactionsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      core_pb.MarkedTransaction.serializeBinaryToWriter
    );
  }
  f = message.getBlockHash();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getBlockchain();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * repeated bc.core.MarkedTransaction marked_transactions = 1;
 * @return {!Array<!proto.bc.core.MarkedTransaction>}
 */
proto.bc.rover.MarkedTxsReq.prototype.getMarkedTransactionsList = function() {
  return /** @type{!Array<!proto.bc.core.MarkedTransaction>} */ (
    jspb.Message.getRepeatedWrapperField(this, core_pb.MarkedTransaction, 1));
};


/**
 * @param {!Array<!proto.bc.core.MarkedTransaction>} value
 * @return {!proto.bc.rover.MarkedTxsReq} returns this
*/
proto.bc.rover.MarkedTxsReq.prototype.setMarkedTransactionsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.bc.core.MarkedTransaction=} opt_value
 * @param {number=} opt_index
 * @return {!proto.bc.core.MarkedTransaction}
 */
proto.bc.rover.MarkedTxsReq.prototype.addMarkedTransactions = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.bc.core.MarkedTransaction, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.bc.rover.MarkedTxsReq} returns this
 */
proto.bc.rover.MarkedTxsReq.prototype.clearMarkedTransactionsList = function() {
  return this.setMarkedTransactionsList([]);
};


/**
 * optional string block_hash = 2;
 * @return {string}
 */
proto.bc.rover.MarkedTxsReq.prototype.getBlockHash = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.bc.rover.MarkedTxsReq} returns this
 */
proto.bc.rover.MarkedTxsReq.prototype.setBlockHash = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string blockchain = 3;
 * @return {string}
 */
proto.bc.rover.MarkedTxsReq.prototype.getBlockchain = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.bc.rover.MarkedTxsReq} returns this
 */
proto.bc.rover.MarkedTxsReq.prototype.setBlockchain = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.bc.rover.QueuedMarkedTxsResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bc.rover.QueuedMarkedTxsResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.bc.rover.QueuedMarkedTxsResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bc.rover.QueuedMarkedTxsResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bc.rover.QueuedMarkedTxsResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    markedTransactionsList: jspb.Message.toObjectList(msg.getMarkedTransactionsList(),
    core_pb.MarkedTransaction.toObject, includeInstance),
    blockHash: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bc.rover.QueuedMarkedTxsResponse}
 */
proto.bc.rover.QueuedMarkedTxsResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bc.rover.QueuedMarkedTxsResponse;
  return proto.bc.rover.QueuedMarkedTxsResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bc.rover.QueuedMarkedTxsResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bc.rover.QueuedMarkedTxsResponse}
 */
proto.bc.rover.QueuedMarkedTxsResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new core_pb.MarkedTransaction;
      reader.readMessage(value,core_pb.MarkedTransaction.deserializeBinaryFromReader);
      msg.addMarkedTransactions(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setBlockHash(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bc.rover.QueuedMarkedTxsResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bc.rover.QueuedMarkedTxsResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bc.rover.QueuedMarkedTxsResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bc.rover.QueuedMarkedTxsResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMarkedTransactionsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      core_pb.MarkedTransaction.serializeBinaryToWriter
    );
  }
  f = message.getBlockHash();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * repeated bc.core.MarkedTransaction marked_transactions = 1;
 * @return {!Array<!proto.bc.core.MarkedTransaction>}
 */
proto.bc.rover.QueuedMarkedTxsResponse.prototype.getMarkedTransactionsList = function() {
  return /** @type{!Array<!proto.bc.core.MarkedTransaction>} */ (
    jspb.Message.getRepeatedWrapperField(this, core_pb.MarkedTransaction, 1));
};


/**
 * @param {!Array<!proto.bc.core.MarkedTransaction>} value
 * @return {!proto.bc.rover.QueuedMarkedTxsResponse} returns this
*/
proto.bc.rover.QueuedMarkedTxsResponse.prototype.setMarkedTransactionsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.bc.core.MarkedTransaction=} opt_value
 * @param {number=} opt_index
 * @return {!proto.bc.core.MarkedTransaction}
 */
proto.bc.rover.QueuedMarkedTxsResponse.prototype.addMarkedTransactions = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.bc.core.MarkedTransaction, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.bc.rover.QueuedMarkedTxsResponse} returns this
 */
proto.bc.rover.QueuedMarkedTxsResponse.prototype.clearMarkedTransactionsList = function() {
  return this.setMarkedTransactionsList([]);
};


/**
 * optional string block_hash = 2;
 * @return {string}
 */
proto.bc.rover.QueuedMarkedTxsResponse.prototype.getBlockHash = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.bc.rover.QueuedMarkedTxsResponse} returns this
 */
proto.bc.rover.QueuedMarkedTxsResponse.prototype.setBlockHash = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * @enum {number}
 */
proto.bc.rover.RoverMessageType = {
  FETCHBLOCK: 0,
  REQUESTRESYNC: 1,
  ROVER_BLOCK_RANGE: 2,
  LATESTBLOCK: 3
};

goog.object.extend(exports, proto.bc.rover);
